## Alerts Collection [/v0/history/alerts/{user_id}{?limit}]

+ Parameters
    + user_id (UUID) - Identifier of the User in the form of a UUID
    + limit (optional, Number) - How many Alerts to return. Max is 1000. Default is 1000.

## List all Alerts of a User [GET]

+ Response 200 (application/json)

+ Attributes (AlertsReturn)
