# Group Dashboard

## Dashboard [/v0/users/{user_id}/dashboard{?since}{?until}{?fields}]

+ Parameters
    + user_id (UUID) - Identifier of the User in the form of a UUID
    + since (timestamp) - blabla
    + until (timestamp) - blabla
    + fields (list) - blabla

### List all Reminders of a User [GET]

+ Response 200 (application/json)
+ Attributes (ReminderGET)
